assemblers/http_matcher.go, assemblers/tcp_reader.go
httpMatcher and its directions confuse me every time I revisit it. So in reviewing #157, I thought I would add more comments and rename some variables to decrease cognitive load in reading this code.
- Add some more doc comments and variable renaming/refactoring to httpMatcher
The new tests still pass! Do these comments and names make sense?
=> maint: add more comments and some var name refactoring to httpMatcher

main.go, main_test.go, utils/k8sutils.go
- Closes #133 
* update semconv usage to v1.21.0
* `http.response.body.size` (no change, but use semconv constant)
* `http.status_code` -> `http.response.status_code`
* `http.request.body.size` (no change, but use constant)
* `http.method` -> `http.request.method`
* `http.url` -> `url.path`
"RequestURI is the unmodified request-target of the Request-Line (RFC 7230, Section 3.1.1) as sent by the client to a server." So RequestURI is the path + query params. `url.path` is the closest to correct attribute to set until we opt to do more parsing of a request.
* `net.sock.host.addr` -> `client.socket.address`
* `destination.address` -> `server.socket.address`
Run the agent!
Is now the time to add transform unit tests or smoke tests? It would make changes to event output more visible in PRs.
=> feat: update to OTel semconv v1.21.0

config/config.go, config/config_test.go, main.go, smoke-tests/deployment.yaml, utils/k8sutils.go
- Closes #224 
Decorate events with the agent's metadata using the [Downward API](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/):
- `meta.agent.node.ip`
- `meta.agent.node.name`
- `meta.agent.serviceaccount.name`
- `meta.agent.pod.ip`
- `meta.agent.pod.name`
Note: Because we use `hostnetwork` in our deployments, host IP and pod IP are the same.
Events in Honeycomb have the agent's metadata
=> feat: Add agent k8s metadata to events

main.go
- agent's telemetry export requests didn't have agent information in the user-agent
- gotta set the user-agent in libhoney before calling init
Run locally and check the user-agent captured by shepherd telemetry
=> fix: append agent info to user-agent

DEVELOPING.md, README.md, examples/ns.yaml, examples/secret-honeycomb.yaml
A few more tweaks to the README for quickstart example instructions.
- Replace namespace and secret resource files with kubectl commands
- Remove unused namespace and secret resource files
- Remove reference to GITHUB_TOKEN and BASE64 in developing.md
Instructions for running the agent using quick start guide is simpler.
=> docs: Replace namespace and secret files with kubectl cmds in README

Dockerfile, Dockerfile.test, Makefile
We maintain two Dockerfiles, one for test and one for building and tagging. This has a maintenance burden of updating both dockerfiles whenever changes are needed.
This PR consolidates both Dockerfiles and uses build stages for test and build so we can target what stage we want.
- Consolidates Dockerfile Dockerfile.test by adding test build stage
- Remove unused clang and llvm dependencies from base stage
- Update Makefile docker-build and docker-test targets to set the desired docker build stage
We now only have one dockerfile we have to maintain and both both build and test makefile targets use the same one.
=> maint: Consolidate dockerfiles and update deps

.gitignore
We have a .gitignore entry for .env files to make local development easier. However, it only supports .env files and it would be nice to support direnv's .envrc files too.
- Update .gitignore rule to allow both .env and .envrc files
Both .env and .envrc files are ignored by git.
=> maint: Update gitignore for direnv file names

assemblers/tcp_assembler.go, handlers/event_handler.go, handlers/libhoney_event_handler.go, handlers/libhoney_event_handler_test.go, main.go
- followup to #230
- closes #228
- closes #237
Use a sync.WaitGroup to ensure that both an assembler and an event handler have stopped generating data before clean-up and process exit.
Behind the curtain, the assembler is using the libhoney client managed within the event handler to ship assembler statistics. Closing that libhoney client has moved from the case statement in Start() to a separate Close() function on the event handler that is called after the wait group count indicates that all our internal routines have ended their loops.
How much of this interface is kept in an OTLP-flavored event handler (and stats producer?) remains TBD.
No more intermittent panics on process exit?
=> fix: add a waitgroup to coordinate shutdown

.tool-versions, Dockerfile, go.mod
Current benefit: this removes a warning from my macOS dev environment during builds.
ld: warning:
'/private/var/folders/c_/shenanigans/T/go-link-2592252367/go.o'
has malformed LC_DYSYMTAB, expected 127 undefined symbols to
start at index 56715, found 133 undefined symbols starting at
index 84
Newer Go is better Go, right?
=> maint: update target go version 1.20 -> 1.21

Dockerfile, Makefile
When called without a target, docker build produces an image based on the final stage in a multi-stage Dockerfile. This rearranges our Dockerfile so that the default is the runnable agent image and not the final state of compiling and testing.
=> fix: default Dockerfile build to the runnable agent stage

handlers/libhoney_event_handler.go, handlers/libhoney_event_handler_test.go
Distinguish between server (status >= 500) and client (500 > status >= 400) errors by noting that in the value for the error field instead of only marking error as true or false.
=> feat: set error field if HTTP status >= 400

README.md
The agent should indicate what Kubernetes platforms it supports.
- Closes #3
- Adds a section to the repositories README that indicates what Kubernetes platforms are supported.
The list of supported Kubernetes platforms is visible in the README.
=> docs: Add supported k8s platforms to README

assemblers/tcp_reader.go, assemblers/tcp_reader_test.go
When processing HTTP request/response pairs, the header structs contain a lot of information we do not care about. From profiling data, we can see a large portion of the agent's live bytes are coming from `textproto.readMimeHeader()`, where headers are created. These bytes are held until the request/response pair is processed.
This PR adds extracts a copy of the header entries we care about and replaces the Header struct on the request/response, meaning the previous larger Header struct can be GC'd earlier and not wait for pairing to complete.
- Closes #253
- Add new extractHeader function that creates a new Header and copies header key/values we want to keep
- Initially we only keep "User-Agent" - more can be added in the future
- Update HTTP request and response parse funcs to use new …
=> feat: Only keep HTTP headers we want to keep

smoke-tests/greetings.yaml
- Easier testing with greeting services
- Use `ClusterIP` instead of `LoadBalancer` type in name, message, and year services to get better event telemetry in Honeycomb
- Add simple alpine pod with curl installed to easily shell in and curl another pod from within the cluster, without 
You can hit the frontend endpoint from localhost in your console with `curl localhost:7777/greeting` and you can hit the frontend endpoint from the alpine image with the IP address of the pod, e.g. `curl 10.1.5.100:7777/greeting`
=> docs: update greetings example service for easier testing

config/config.go, main.go, smoke-tests/deployment.yaml
- Closes #264 
- Check endpoint and if it differs from our default, skip the api key validation
- Move the Config Validate below the logging of config values; that way, if there is something wrong, the config values are printed out first for easier troubleshooting if it fails.
I'd considered some refactoring to pull out defaults and use a variable instead of hardcoding here, but wasn't sure it was worth the extra cleanup for this rare use case.
Set an incorrect API Key. With no change to endpoint, or endpoint set to `"https://api.honeycomb.io"`, agent pod should fail to start because of invalid key - and should log the config options followed by the fatal error. With a different endpoint, agent should start with no failure.
=> fix: skip key validation if endpoint is different

CHANGELOG.md, main.go
Prepares the v0.0.20-alpha release.
- Add changelog entry
- Update agent version
**Note**: The release includes references to the following PRs that are not merged yet:
- #259 
- #266 
I've also used the @ notation for contributor names to see if GitHub automatically links them. 
A new release of the agent can be published.
=> rel: Prepare v0.0.20-alpha release

config/config.go, config/config_test.go, handlers/libhoney_event_handler.go, handlers/libhoney_event_handler_test.go, smoke-tests/deployment.yaml
During event processing og HTTP request/response pairs, the HTTP URL is added to the output event. This potentially could sensitive information from the url path and or query string. 
This PR adds an opt-in configuration option to enable HTTP URL capture. 
- Works toward #214 
- Adds new configuration option to determine whether HTTP URLs are recorded in events, defaults to `false`
- Set the new config option by reading the new `INCLUDE_REQUEST_URL` env var
- Use new config option during processing to decide if the HTTP URL is added to libhoney event
- Add tests to check both the default config value is `false` and the config can be updated by using the env var
- Add example of setting the env var in the smoke test deployment yaml
The agent now requires user to opt-in to recording HTTP …
=> feat: Add opt-in config option for HTTP URL

Dockerfile
- More in service to #128 
Remove the cached repository lists to reduce the image size by another ~40 MB.
247MB -> 206MB :: ~20% smaller!
=> maint: even smaller image size with no cached APT repo lists

examples/quickstart.yaml, smoke-tests/deployment.yaml
- In service to #273
- add resource limits to smoke test deployment manifest
- add missed variables to quickstart example for k8s metadata
- add note for why the k8s variables are used
Quickstart includes k8s metadata; smoke test deployment can have limits uncommented and work as expected
These values may need to be adjusted based on traffic but this starter kept under limit running a load test of 8000 users spawning at 100/sec.
=> maint: include k8s vars in quickstart and add resource limits to test manifest

config/config.go, config/config_test.go
- Closes #272 
- Extend list of supported HTTP methods in the bpf filter used to capture network activity to include HEAD, OPTIONS, PATCH, TRACE and CONNECT
- Breaks up the components that make up the capture filter. Lots of words written about what the pieces do.
- This is ripe for extraction into an HTTP-flavored subpackage.
- Tests for the filter generator
More HTTP methods will be captured and have events created from.
=> feat: capture more types of HTTP requests

assemblers/tcp_assembler.go, debug/debug_service.go
There are a number of start-up messages that should be at debug level instead of Info to get keep the log clear. This PR tidies up some logging. 
- Remove unneccary log entries in assembler and debug service
- Change pcap config log to debug
The log entries when starting the agent are a little cleaner.
=> maint: Tidy start-up logging

README.md, smoke-tests/deployment.yaml
- request url is enabled by default, example should disable
- http_headers are options now
- update smoke test deployment with new environment variables
- update the config table in the readme with the new environment variables
- some formatting cleanup from my editor
=> maint: update smoke test deployment for new env vars

handlers/libhoney_event_handler.go, handlers/libhoney_event_handler_test.go
- Closes #288 
- add fields for `http.request.headers` and `http.response.headers` and accompanying unit tests. #277 added all the logic for configuring the `HTTP_HEADERS` to be extracted, and this PR adds the headers to the actual event to be sent to Honeycomb.
This is the smaller implementation mentioned in the issue. We could (/should?) have individual attributes for each key, but I figured this could be a faster fix to start since we've already published with the expectation of HTTP_HEADERS working.
Run the agent with something like the example greeting service and see the attributes in Honeycomb.
The default captures just the User-Agent:
- `http.request.headers`
- example: `"{\"User-Agent\":[\"Go-http-client/1.1\"]}"`
- `http.response.headers`
- example: `"{}"`
If for example the …
=> fix: add headers to honeycomb event

handlers/otel_handler.go, handlers/otel_handler_test.go, smoke-tests/deployment.yaml
More closely follows sem conv when handing headers in the otel handler.
=> Follow OTel semantic conventions when converting headers

handlers/otel_handler_test.go
Fixes a flaky test that compares two arrays and will fail if the order is incorrect.
- Update OTel header tests to use contains assertion instead of comparing two slices
The tests are no longer flakey.
=> fix: Update OTel header tests to use contains instead of comparing slices directly

CHANGELOG.md, go.mod, main.go
- release prep for v0.0.23-alpha
- bump version number
- update changelog
- bonus: tidy `go.mod`
- The two `require()` blocks of indirect dependencies was confusing some dev tooling into thinking deps weren't installed.
- Combined the block, ran `go mod tidy`, and noted that there are no changes to `go.sum`.
=> rel: prep v0.0.23-alpha

.github/dependabot.yml
Adds a dependency group to dependabot config so related packages are updated together. 
- Add groups for otel to dependabot config
Dependabot will group OTel packages into PRs.
=> maint: Add otel dependabot group

README.md
Adds documentation on expected behaviour for generating events for different types of communication (eg cluster ingress/egress and pod-to-pod). 
- Closes #115 
- Adds a section to the project's README to describe expected behaviour for event generation
- Adds note after the above section to indicate expected behaviour for pod-to-pod events
The project README has docs on expected event generation behaviour.
=> docs: Document expected behaviour for event creation

config/config.go, config/config_test.go, smoke-tests/deployment.yaml
The agent currently defaults to using libhoney to send events. This PR updates the agent to default to OTel handler.
- Closes #305 
- Update config default to `otel` instead of `libhoney`
- Updates smoke-test deployment's example headers to show how to use libhoney handler
- Add unit test to verify default config value
The agent defaults to using OTel to send events
=> feat: Make OTel handler default

README.md, smoke-tests/deployment.yaml
- With OTel as default handler now, additional attributes should be defined in `OTEL_RESOURCE_ATTRIBUTES`
- Now that `Traceparent` is available and default, add to smoke test deployment for `HTTP_HEADERS`
=> docs: update configs in readme and smoke-test deployment

utils/cached_k8s_client.go
- Closes #313
When looking through the documentation for the selector matching functionality, I noticed a [comment](https://github.com/kubernetes/apimachinery/blob/fa98d6eaedb4caccd69fc07d90bbb6a1e551f00f/pkg/labels/selector.go#L941-L942) about the underlying data being copied due to it being treated as potentially mutable.
We call the `GetServiceForPod` method of the cached k8s client at least twice per event when sending [Honeycomb events](https://github.com/honeycombio/honeycomb-network-agent/blob/5cc35d2b1e1f2377199405b9d3889a34b6cafb7e/handlers/libhoney_event_handler.go#L117-L118) and when [creating spans in the OTEL handler](https://github.com/honeycombio/honeycomb-network-agent/blob/5cc35d2b1e1f2377199405b9d3889a34b6cafb7e/handlers/otel_handler.go#L132-L140). This means the same …
=> fix: use ValidatedSetSelector to reduce memory usage in k8s client

Makefile, smoke-tests/echoserver.yaml
Makes the smoke tests run more reliably. 
- Closes #320
- Update rollout timeouts for network agent and echoserver to 60 seconds, they return as soon as they complete so it's okay to have a long timeout
- Decrease the number of echoserver replicas from 5 to 1, we don't need 5 and it increases the rollout time
- Update the `smokey_copy_output` makefile target to remove old version of the file if present and increase the wait time from 12 to 30 seconds
The smoke tests run more reliably both in CI and locally.
=> maint: Make smoke tests more reliable

CHANGELOG.md, main.go
Prepares the first beta release.
- update version to v0.1.0-beta
- add changelog entry
The first beta release of the network agent can be published.
=> rel: Prepare v0.1.0-beta release

smoke-tests/smoke-job.yaml, smoke-tests/verify.bats
- Fixes failed test for updated curl image ([see failing test here](https://github.com/honeycombio/honeycomb-network-agent/actions/runs/7144635179/job/19458679899?pr=325))
- specify tag in curl docker image
- update smoke test for curl version
passing smoke tests
=> maint: update curl in smoke tests

.github/release.yml
- we auto-generate release notes and if things aren't tagged they go into "other changes"
- dependencies and documentation PRs are generally considered maintenance, so if it has that label, it should get auto-categorized as maintenance on the auto-generated release notes
=> maint: add deps and docs to maintenance in release

handlers/libhoney_event_handler.go, handlers/otel_handler.go, smoke-tests/verify.bats
- Updates #328 
- Add `honeycomb.agent.name` and `honeycomb.agent.version` as resource attributes to help distinguish where telemetry came from. This is similar to the `honeycomb.distro.*` attributes in our distros, and `telemetry.sdk.*` attributes from otel.
- Update smoke test to check for presence of the name
Telemetry should include those fields, with no other changes
=> feat: add honeycomb resource attributes

CHANGELOG.md, main.go
Prepares the next release of the network agent.
- Upadate version to v0.2.0-beta
- Add changelog entry
The next release of the agent can be published.
=> rel: Prepare the v0.2.0-beta release

CHANGELOG.md, main.go
Prepares the next release of the Network Agent.
- Updates version to 0.2.1-beta in main.go
- Adds changelog entry
The new version can be tagged and published.
=> rel: Prepare v0.2.1-beta release

.github/dependabot.yml
Updates dependabot config reviewers and schdedule.
- Update reviewers to @honeycombio/pipeline-team 
- Update schedule to monthly
=> chore: Update dependabot reviewers and schedule
